export type Tone = 'primary' | 'secondary' | 'tertiary' | 'muted' | 'inherit'
export type Variant = 'primary' | 'neutral' | 'success' | 'warning' | 'danger' | 'info'
export type Block = 'p' | 'h6' | 'h5' | 'h4' | 'h3' | 'h2' | 'h1'
export type Inline =
  | 'span'
  | 'small'
  | 'strong'
  | 'b'
  | 'em'
  | 'i'
  | 'q'
  | 'del'
  | 's'
  | 'ins'
  | 'u'
  | 'code'
  | 'mark'
  | 'sub'
  | 'sup'
export type Font = 'base' | 'display' | 'code' | 'emphasis'
export type Size = 'sm' | 'base' | 'h5' | 'h4' | 'h3' | 'h2' | 'h1'
export type Weight =
  | 'thin'
  | 'extralight'
  | 'light'
  | 'normal'
  | 'medium'
  | 'semibold'
  | 'bold'
  | 'extrabold'
  | 'black'
  | 'inherit'
export type Leading = 'sm' | 'base' | 'lg'
export type TextAlign = 'left' | 'center' | 'right' | 'justify'
