import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

const GOOGLE_FONTS_CSS_URL =
  'https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=Merriweather:ital,opsz,wdth,wght@0,18..144,87..112,300..900;1,18..144,87..112,300..900&family=Nunito+Sans:wght@400..700&family=Outfit:wght@100..900&family=Quicksand:wght@300..700&family=Space+Grotesk:wght@300..700&display=swap'

const FONT_OUTPUT_DIR = 'public/fonts/google'
const GENERATED_CSS_OUTPUT_PATH = 'src/styles/fonts.generated.scss'

const FONT_SUBSETS: readonly string[] = ['latin', 'latin-ext']

const USER_AGENT =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:153.0) Gecko/20100101 Firefox/153.0'

type FontFaceBlock = {
  subset: string
  css: string
  url: string
  family: string
  style: string
}

async function fetchText(url: string): Promise<string> {
  const response: Response = await fetch(url, {
    headers: {
      'User-Agent': USER_AGENT,
    },
  })

  if (!response.ok) {
    throw new Error(`Failed to fetch Google Fonts CSS: HTTP ${response.status}`)
  }

  return response.text()
}

async function downloadFile(url: string, outputPath: string): Promise<void> {
  const response: Response = await fetch(url, {
    headers: {
      'User-Agent': USER_AGENT,
    },
  })

  if (!response.ok) {
    throw new Error(`Failed to download font file: HTTP ${response.status} ${url}`)
  }

  const fileBuffer: Buffer = Buffer.from(await response.arrayBuffer())

  await writeFile(outputPath, fileBuffer)
}

function getDeclarationValue(css: string, propertyName: string): string {
  const pattern = new RegExp(`${propertyName}:\\s*([^;]+);`)
  const match: RegExpMatchArray | null = css.match(pattern)

  return match?.[1]?.trim().replaceAll("'", '') ?? ''
}

function getFontUrl(css: string): string {
  const match: RegExpMatchArray | null = css.match(
    /url\((https:\/\/fonts\.gstatic\.com\/[^)]+?\.woff2)\)/,
  )

  return match?.[1] ?? ''
}

function getSlug(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replaceAll(/\s+/g, '-')
    .replaceAll(/[^a-z0-9-]/g, '')
}

function getFontFilename(block: FontFaceBlock): string {
  const family: string = getSlug(block.family)
  const style: string = getSlug(block.style || 'normal')
  const subset: string = getSlug(block.subset)
  const hash: string = createHash('sha256').update(block.url).digest('hex').slice(0, 8)

  return `${family}-${style}-${subset}-${hash}.woff2`
}

function parseFontFaceBlocks(css: string): FontFaceBlock[] {
  const blocks: FontFaceBlock[] = []
  const pattern = /\/\*\s*([^*]+?)\s*\*\/\s*(@font-face\s*{[^}]+})/g

  for (const match of css.matchAll(pattern)) {
    const subset: string | undefined = match[1]?.trim()
    const blockCss: string | undefined = match[2]
    const fullCss: string | undefined = match[0]

    if (!subset || !blockCss || !fullCss) continue
    if (!FONT_SUBSETS.includes(subset)) continue

    const url: string = getFontUrl(blockCss)

    if (!url) continue

    blocks.push({
      subset,
      css: fullCss,
      url,
      family: getDeclarationValue(blockCss, 'font-family'),
      style: getDeclarationValue(blockCss, 'font-style'),
    })
  }

  return blocks
}

async function main(): Promise<void> {
  await mkdir(FONT_OUTPUT_DIR, { recursive: true })

  const remoteCss: string = await fetchText(GOOGLE_FONTS_CSS_URL)
  const fontFaceBlocks: FontFaceBlock[] = parseFontFaceBlocks(remoteCss)

  if (fontFaceBlocks.length === 0) {
    throw new Error('No matching Google Fonts @font-face blocks were found.')
  }

  const localCssBlocks: string[] = []

  for (const block of fontFaceBlocks) {
    const filename: string = getFontFilename(block)
    const outputPath: string = join(FONT_OUTPUT_DIR, filename)
    const publicPath: string = `/fonts/google/${filename}`

    console.log(`Downloading ${block.family} ${block.style} ${block.subset}...`)

    await downloadFile(block.url, outputPath)

    localCssBlocks.push(block.css.replace(block.url, publicPath))
  }

  const generatedCss: string = [
    '/*',
    ' * Generated by scripts/download-google-fonts.ts.',
    ' * Do not edit this file by hand.',
    ' */',
    '',
    ...localCssBlocks,
    '',
  ].join('\n')

  await mkdir(dirname(GENERATED_CSS_OUTPUT_PATH), { recursive: true })
  await writeFile(GENERATED_CSS_OUTPUT_PATH, generatedCss)

  console.log(`Downloaded ${fontFaceBlocks.length} font files.`)
  console.log(`Generated ${GENERATED_CSS_OUTPUT_PATH}.`)
}

main().catch((error: unknown): void => {
  console.error(error instanceof Error ? error.message : error)

  process.exitCode = 1
})
